apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: wp-demo
  labels:
    app: wordpress
spec:
  storageClassName: cinder-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
